[project]
name = "ansible-collection-dev"
version = "0.3.0"
description = "Ansible collection supporting development tasks for Ansible roles."
authors = ["Jonas Mauer"]
license = "MIT"
keywords = ["ansible", "collection", "roles", "development", "modules"]
repository = "https://github.com/jomrr/ansible-collection-dev"

[tool.commitizen]
name = "cz_conventional_commits"

[tool.semantic_release]
commit_message = "build(release): version {version}"
major_on_zero = false
upload_to_pypi = false
upload_to_vcs_release = true
version_variables = [
    "galaxy.yml:version",
]
version_toml = [
    "pyproject.toml:project.version",
]
